
server:
  port: 8000

# Keycloak configuration
keycloak:
  auth-server-url: "http://localhost:8888/auth"
  realm: foo-dev
  resource: foo-dev
  public-client: true
  principal-attribute: preferred_username
  ssl-required: none
  confidential-port: 443
  token-store: cookie


logging:
  level:
    ROOT: INFO
    de.dev.eth0: DEBUG
    org.keycloak: DEBUG